# Build forego
FROM golang:1.21.2 as go-builder

WORKDIR /build

# Install the dependencies
COPY . .
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o forego . \
   && go clean -cache

FROM debian:12.1-slim

# Install Forego
COPY --from=go-builder /build/forego /usr/local/bin/forego

COPY /app /app
WORKDIR /app

CMD ["forego", "start", "-r"]
